apiVersion: v1
kind: Service
metadata:
  name: local-redis-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: local-redis
    app.kubernetes.io/managed-by: Helm
  ports:
    - port: 6379
      nodePort: 30002
      targetPort: 6379
      protocol: TCP
