apiVersion: v1
kind: Service
metadata:
  name: local-postgresql-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: local-postgresql
    app.kubernetes.io/managed-by: Helm
  ports:
    - port: 5432
      nodePort: 30001
      targetPort: 5432
      protocol: TCP
