apiVersion: v1
kind: Service
metadata:
  name: local-mysql-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: local-mysql
    app.kubernetes.io/managed-by: Helm
  ports:
    - port: 3306
      nodePort: 30000
      targetPort: 3306
      protocol: TCP
