apiVersion: v1
kind: Service
metadata:
  name: local-etcd-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: local-etcd
    app.kubernetes.io/managed-by: Helm
  ports:
    - port: 2379
      nodePort: 30003
      targetPort: 2379
      protocol: TCP
